name: Frontend build&test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  GITHUB_TOKEN: ${{ github.token }}
  IMAGE_NAME: winter23-frontend

jobs:
  build-test:
      name: Build project
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: /home/runner/work/winter23/winter23/measurements_frontend/measurements/package-lock.json
      - run: npm i
        working-directory: measurements_frontend/measurements
      - run: npm run build --if-present
        working-directory: measurements_frontend/measurements
      - name: zip build
        run: zip -r build/artifact.zip build
        working-directory: measurements_frontend/measurements
      - uses: actions/upload-artifact@v1
        with:
          name: react_build
          path: measurements_frontend/measurements/build
      - run: npm test
        working-directory: measurements_frontend/measurements

  docker:
        name: Build and upload docker image
        needs: build-test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Build the Docker image
            working-directory: measurements_frontend/measurements
            run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          - name: Log in to Docker Hub
            uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
            with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Build and push Docker image
            run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
            
  release:    
     permissions: write-all
     name: Create release and upload asset
     needs: build-test
     runs-on: ubuntu-latest
     steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H:%M')"
      - name: Get current tag
        id: tag
        run: echo "::set-output name=tag::$(date +'%Y.%m.%d.%H.%M')"
      - uses: actions/download-artifact@v1
        with:
             path: measurements_frontend/measurements
             name: react_build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Frontend-Nightly-${{ steps.date.outputs.date }}
          tag_name: frontend_nightly.${{ steps.tag.outputs.tag }}      
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: measurements_frontend/measurements/artifact.zip
          asset_name: Frontend-Nightly-${{ steps.date.outputs.date }}.zip
          asset_content_type: application/zip
